/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Interfaz.Modelos.Administrador;
import Interfaz.Modelos.Orden;
import Interfaz.Modelos.PlatoFuerte;
import Interfaz.Modelos.Postre;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author angel
 */
public class GestionOrdenes extends javax.swing.JPanel {

    private Administrador administrador;
    private Orden nuevaOrden = new Orden();

    /**
     * Creates new form GestionOrdenes
     */
    public GestionOrdenes(Administrador administrador) {
        this.administrador = administrador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lectorNumOrden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lectorFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lectorNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lectorDescuento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resultadoTotal = new javax.swing.JTextField();
        botonAgregarOrden = new javax.swing.JButton();
        definirFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eleccionPlatoFuerte = new javax.swing.JComboBox<>();
        eleccionPostre = new javax.swing.JComboBox<>();

        jLabel1.setText("Número de orden");

        lectorNumOrden.setEditable(false);
        lectorNumOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectorNumOrdenActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese la fecha");

        lectorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectorFechaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre del cliente");

        jLabel4.setText("Elija el plato fuerte");

        jLabel5.setText("Elija el postre");

        jLabel6.setText("Descuento (compras mayores a 10000)");

        jLabel7.setText("Total de la comprar");

        resultadoTotal.setEditable(false);

        botonAgregarOrden.setText("Finalizar orden");
        botonAgregarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarOrdenActionPerformed(evt);
            }
        });

        definirFecha.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        definirFecha.setText("El estado de la fecha aparece aquí");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("El número de orden es automático");

        this.actualizarInterfaz();
        eleccionPlatoFuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleccionPlatoFuerteActionPerformed(evt);
            }
        });

        eleccionPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleccionPostreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(eleccionPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eleccionPlatoFuerte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lectorNombreCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lectorNumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(resultadoTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lectorDescuento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(botonAgregarOrden)
                            .addComponent(jLabel8)
                            .addComponent(definirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lectorNumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(definirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lectorNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eleccionPlatoFuerte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eleccionPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lectorDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(botonAgregarOrden)
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lectorNumOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectorNumOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectorNumOrdenActionPerformed

    private void lectorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectorFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectorFechaActionPerformed

    private void botonAgregarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarOrdenActionPerformed
        // TODO add your handling code here:
        int numOrden = this.administrador.getListaOrdenes().size() + 1;
        lectorNumOrden.setText(String.valueOf(numOrden));
        String fechaIngresada = obtenerFecha();
        String nombreCliente = lectorNombreCliente.getText();
        int descuentoAplicado = Integer.parseInt(lectorDescuento.getText());

        this.nuevaOrden.setNumOrden(numOrden);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/yyyy"); // Define the date format
        try {
            Date fecha = sdf.parse(fechaIngresada);  // Parsea la string en un objeto de tipo Date
            this.nuevaOrden.setFecha(fecha);
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.nuevaOrden.setNombreCliente(nombreCliente);
        this.nuevaOrden.setDescuento(descuentoAplicado);

    }//GEN-LAST:event_botonAgregarOrdenActionPerformed

    private void eleccionPlatoFuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleccionPlatoFuerteActionPerformed
        // TODO add your handling code here:

        System.out.println(this.eleccionPlatoFuerte.getSelectedIndex());
        int indicePlatoFuerte = this.eleccionPlatoFuerte.getSelectedIndex();
        if (indicePlatoFuerte >= 0) {
            PlatoFuerte platoFuerte = this.administrador.getListaPlatosFuertes().get(indicePlatoFuerte);
            this.nuevaOrden.recibirPlatoFuerte(platoFuerte);
        }

    }//GEN-LAST:event_eleccionPlatoFuerteActionPerformed

    private void eleccionPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleccionPostreActionPerformed
        // TODO add your handling code here:
        int indicePostre = this.eleccionPostre.getSelectedIndex();
        if (indicePostre >= 0) {
            Postre postre = this.administrador.getListaPostres().get(indicePostre);
            this.nuevaOrden.recibirPostre(postre);
        }

    }//GEN-LAST:event_eleccionPostreActionPerformed

    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

    public String obtenerFecha() {
        String fechaOrden = new String();
        String fechaIngresada = lectorFecha.getText();
        Date fechaObtenida = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MMM/yyyy", Locale.forLanguageTag("es-ES"));//Se define e inicializa una fecha de tipo SimpleDateFormat para que se defina el formato esperato y que permita el ingreso de datos en idioma español
        formatoFecha.setLenient(false);//El método setLenient con el parámetro false permite que la fecha lance exepciones y se puede validar si hay algún error al momento de ingresar la fecha

        try {
            fechaObtenida = formatoFecha.parse(fechaIngresada);
            SimpleDateFormat mostrarFecha = new SimpleDateFormat("dd/MMM/yyyy");
            fechaOrden = mostrarFecha.format(fechaObtenida);
            definirFecha.setText("Fecha: " + fechaOrden);

        } catch (ParseException e) {
            definirFecha.setText("El formato de la fecha debe ser dd//MMM/yyyy");
            lectorFecha.setText("");
        }
        return fechaOrden;
    }

    public void actualizarInterfaz() {

        eleccionPlatoFuerte.removeAllItems();
        for (PlatoFuerte platoFuerte : this.administrador.getListaPlatosFuertes()) {

            eleccionPlatoFuerte.addItem(platoFuerte.getNombre());
        }

        eleccionPostre.removeAllItems();
        for (Postre postre : this.administrador.getListaPostres()) {

            eleccionPostre.addItem(postre.getNombre());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarOrden;
    private javax.swing.JLabel definirFecha;
    private javax.swing.JComboBox<String> eleccionPlatoFuerte;
    private javax.swing.JComboBox<String> eleccionPostre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lectorDescuento;
    private javax.swing.JTextField lectorFecha;
    private javax.swing.JTextField lectorNombreCliente;
    private javax.swing.JTextField lectorNumOrden;
    private javax.swing.JTextField resultadoTotal;
    // End of variables declaration//GEN-END:variables
}
