package Interfaz;

import Interfaz.Modelos.Administrador;
import java.awt.BorderLayout;
import java.awt.Component;
import java.util.Scanner;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author angel
 */
public class Restaurante extends javax.swing.JFrame {

    Administrador administrador = new Administrador();

    /**
     * Creates new form TrabajarProductos
     */
    public Restaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        tabProductos = new javax.swing.JPanel();
        tabOrdenes = new javax.swing.JPanel();
        tabReporte = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPrincipalStateChanged(evt);
            }
        });

        tabProductos.setLayout(new BorderLayout());
        GestionProductos gestionProductos = new GestionProductos();
        gestionProductos.setAdministrador(administrador);
        gestionProductos.setSize(800,580);
        tabProductos.add(gestionProductos, BorderLayout.CENTER);

        javax.swing.GroupLayout tabProductosLayout = new javax.swing.GroupLayout(tabProductos);
        tabProductos.setLayout(tabProductosLayout);
        tabProductosLayout.setHorizontalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        tabProductosLayout.setVerticalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        tabPrincipal.addTab("Productos", tabProductos);

        tabOrdenes.setLayout(new BorderLayout());
        GestionOrdenes gestionOrdenes = new GestionOrdenes(this.administrador);
        gestionOrdenes.setAdministrador(administrador);
        gestionOrdenes.setSize(800,580);
        tabOrdenes.add(gestionOrdenes, BorderLayout.CENTER);

        javax.swing.GroupLayout tabOrdenesLayout = new javax.swing.GroupLayout(tabOrdenes);
        tabOrdenes.setLayout(tabOrdenesLayout);
        tabOrdenesLayout.setHorizontalGroup(
            tabOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        tabOrdenesLayout.setVerticalGroup(
            tabOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        tabPrincipal.addTab("Órdenes", tabOrdenes);

        javax.swing.GroupLayout tabReporteLayout = new javax.swing.GroupLayout(tabReporte);
        tabReporte.setLayout(tabReporteLayout);
        tabReporteLayout.setHorizontalGroup(
            tabReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        tabReporteLayout.setVerticalGroup(
            tabReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        tabPrincipal.addTab("Reporte", tabReporte);

        tabPrincipal.setSize(800,580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPrincipalStateChanged
        // TODO add your handling code here:
        System.out.println("visible: " + tabPrincipal.getSelectedIndex());

        if (tabPrincipal.getSelectedIndex() == 1) {

            for (Component componente : tabOrdenes.getComponents()) {
                if (componente instanceof GestionOrdenes) {
                    ((GestionOrdenes) componente).actualizarInterfaz();
                }
            }
        }
    }//GEN-LAST:event_tabPrincipalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tabOrdenes;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabReporte;
    // End of variables declaration//GEN-END:variables
}
